name: "Create Okta User"
description: "新しい Okta ユーザーを作成するリクエストフォーム"
title: "[Oktaユーザー作成] "
labels: ["okta", "provisioning"]
assignees: []

# ❗️この version: 2 が必須です！
version: 2

body:
  - type: input
    id: given_name
    attributes:
      label: "名（First Name）"
      description: "ユーザーの名を入力してください"
      placeholder: "Taro"
    validations:
      required: true

  - type: input
    id: family_name
    attributes:
      label: "姓（Last Name）"
      description: "ユーザーの姓を入力してください"
      placeholder: "Yamada"
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: "メールアドレス"
      description: "ユーザーの会社用メールアドレス"
      placeholder: "taro.yamada@example.com"
    validations:
      required: true

  - type: input
    id: display_name
    attributes:
      label: "表示名（任意）"
      placeholder: "Taro Yamada"
    validations:
      required: false

  - type: dropdown
    id: locale
    attributes:
      label: "ロケール"
      options:
        - label: 日本語 (ja-JP)
          value: ja-JP
        - label: 英語 (en-US)
          value: en-US
    validations:
      required: true

  - type: input
    id: external_id
    attributes:
      label: "外部ID（任意）"
      placeholder: "社員番号など"
    validations:
      required: false
