name: "Create Okta User"
description: Oktaへの新規ユーザー登録のリクエストフォーム
title: "【Okta User Request】"
labels: ["okta-user-request"]

body:
  - type: input
    id: given_name
    attributes:
      label: "名（First Name）"
      placeholder: "Taro"
    validations:
      required: true

  - type: input
    id: family_name
    attributes:
      label: "姓（Last Name）"
      placeholder: "Yamada"
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: "メールアドレス"
      placeholder: "taro@example.com"
    validations:
      required: true

  - type: dropdown
    id: reviewer
    attributes:
      label: "レビュワーを選択"
      description: "このユーザーJSONを確認するレビュワーを選んでください"
      options:
        - konmayu
        - yusuke-okazaki
    validations:
      required: true
