name: "Create Okta User"
description: Oktaへの新規ユーザー登録のリクエストフォーム
title: "【Okta User Request】"
labels: ["okta-user-request"]
assignees: []

body:
  - type: input
    id: given_name
    attributes:
      label: "名（First Name）"
      placeholder: "Taro"
    validations:
      required: true

  - type: input
    id: family_name
    attributes:
      label: "姓（Last Name）"
      placeholder: "Yamada"
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: "メールアドレス"
      placeholder: "taro@example.com"
    validations:
      required: true
