name: Generate User JSON

on:
  issues:
    types: [opened]

permissions:
  contents: write  # ✅ GITHUB_TOKEN に push 権限を与える

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Parse issue content
        run: |
          echo "${{ github.event.issue.body }}" > issue_body.txt

          # Markdown形式の見出しに対応（### 見出し の次の行を抽出）
          FIRST_NAME=$(awk '/^###.*名/{getline; print}' issue_body.txt | xargs)
          LAST_NAME=$(awk '/^###.*姓/{getline; print}' issue_body.txt | xargs)
          EMAIL=$(awk '/^###.*メールアドレス/{getline; print}' issue_body.txt | xargs)
          DISPLAY_NAME=$(awk '/^###.*表示名/{getline; print}' issue_body.txt | xargs)
          LOCALE=$(awk '/^###.*ロケール/{getline; print}' issue_body.txt | xargs)
          EXTERNAL_ID=$(awk '/^###.*外部ID/{getline; print}' issue_body.txt | xargs)

          if [ -z "$EMAIL" ]; then
            echo "❌ メールアドレスが空です。Issue本文の形式を確認してください。"
            cat issue_body.txt
            exit 1
          fi

          echo "FIRST_NAME=$FIRST_NAME" >> $GITHUB_ENV
          echo "LAST_NAME=$LAST_NAME" >> $GITHUB_ENV
          echo "EMAIL=$EMAIL" >> $GITHUB_ENV
          echo "DISPLAY_NAME=$DISPLAY_NAME" >> $GITHUB_ENV
          echo "LOCALE=$LOCALE" >> $GITHUB_ENV
          echo "EXTERNAL_ID=$EXTERNAL_ID" >> $GITHUB_ENV

      - name: Create JSON file
        run: |
          mkdir -p public/users

          FILENAME=$(echo "$EMAIL" | sed 's/@/-at-/g' | sed 's/[^a-zA-Z0-9._-]//g')
          JSON_PATH="public/users/${FILENAME}.json"

          cat <<EOF > "$JSON_PATH"
          {
            "schemas": ["urn:ietf:params:scim:schemas:core:2.0:User"],
            "userName": "$EMAIL",
            "name": {
              "givenName": "$FIRST_NAME",
              "familyName": "$LAST_NAME"
            },
            "displayName": "$DISPLAY_NAME",
            "emails": [{
              "primary": true,
              "value": "$EMAIL",
              "type": "work"
            }],
            "locale": "$LOCALE",
            "externalId": "$EXTERNAL_ID",
            "active": true
          }
          EOF

          echo "JSON_PATH=$JSON_PATH" >> $GITHUB_ENV

      - name: Commit & Push JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add "$JSON_PATH"
          git commit -m "Add user JSON for $EMAIL"
          git push origin HEAD
